#!/usr/bin/env bash
#
# curl_test.sh - Simulate crawler/bot requests against a live URL to verify
# that the .htaccess bot-blocker rules generated by replacer.php actually
# work when served through a real web server (Apache/Nginx + PHP).
#
# NOTE: PHP's built-in server (`php -S`) does NOT read .htaccess files.
# Point --url at a vhost served by Apache (mod_rewrite) for real results.
#
# Usage:
#   tests/curl_test.sh --url=<url> --bot=<name>   Send one request as a known bot
#   tests/curl_test.sh --url=<url> --ua="<UA>"    Send one request with a custom User-Agent
#   tests/curl_test.sh --url=<url> --bot=all      Send a request for every known bot
#   tests/curl_test.sh --url=<url> --browser      Send a request as a normal browser
#   tests/curl_test.sh --list                     List known bot names
#
# Options:
#   --url=<url>       Target URL to test (required, except with --list)
#   --bot=<name>      Bot name from the known list, or "all" (see --list)
#   --ua="<string>"   Custom User-Agent string (overrides --bot)
#   --browser         Use a normal desktop browser User-Agent instead of a bot
#   --expect=<code>   Expected HTTP status code (default: 403 for bots, 200 for --browser)
#   -v, --verbose     Print full response headers for each request
#   -h, --help        Show this help
#
# Exit code: 0 if all requests matched their expected status, 1 otherwise.

set -u

SCRIPT_NAME="$(basename "$0")"

# Known crawler bots, kept in sync with the default blocklist in replacer.php
# (see the 'htaccess-bot-blocker' mode). Format: name|User-Agent string
# RewriteEngine On
# RewriteCond %{HTTP_USER_AGENT} (AhrefsBot|SemrushBot|MJ12bot|DotBot|rogerbot|DataForSeoBot|BLEXBot|serpstatbot|Barkrowler|MegaIndex|GPTBot|ClaudeBot|CCBot|PerplexityBot|Bytespider|Amazonbot|meta-externalagent|Google-Extended|GoogleOther|anthropic-ai|Claude-Web) [NC]
# RewriteRule .* - [F,L]
BOTS='
AhrefsBot|Mozilla/5.0 (compatible; AhrefsBot/7.0; +http://ahrefs.com/robot/)
SemrushBot|Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)
MJ12bot|Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)
DotBot|Mozilla/5.0 (compatible; DotBot/1.2; +https://opensiteexplorer.org/dotbot; help@moz.com)
rogerbot|rogerbot/1.0 (http://moz.com/help/pro/what-is-rogerbot, rogerbot-crawler+partnerships@moz.com)
DataForSeoBot|Mozilla/5.0 (compatible; DataForSeoBot/1.0; +https://dataforseo.com/dataforseo-bot)
BLEXBot|Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)
serpstatbot|Mozilla/5.0 (compatible; serpstatbot/2.1; +http://serpstatbot.com/)
Barkrowler|Mozilla/5.0 (compatible; Barkrowler/0.9; +https://babbar.tech/crawler)
MegaIndex|Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +http://megaindex.com/crawler)
GPTBot|Mozilla/5.0 (compatible; GPTBot/1.1; +https://openai.com/gptbot)
ClaudeBot|Mozilla/5.0 (compatible; ClaudeBot/1.0; +claudebot@anthropic.com)
CCBot|CCBot/2.0 (https://commoncrawl.org/faq/)
PerplexityBot|Mozilla/5.0 (compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)
Bytespider|Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; Bytespider; spider-feedback@bytedance.com)
Amazonbot|Mozilla/5.0 (compatible; Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)
meta-externalagent|meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler)
Google-Extended|Mozilla/5.0 (compatible; Google-Extended)
GoogleOther|Mozilla/5.0 (compatible; GoogleOther)
anthropic-ai|anthropic-ai
Claude-Web|Claude-Web/1.0
'

BROWSER_UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"

URL=""
BOT=""
CUSTOM_UA=""
USE_BROWSER=0
EXPECT=""
VERBOSE=0

print_help() {
    sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'
}

lookup_ua() {
    local name="$1"
    echo "$BOTS" | awk -F'|' -v n="$name" 'BEGIN{IGNORECASE=1} $1==n {print $2; found=1} END{exit !found}'
}

list_bots() {
    echo "Known bots:"
    echo "$BOTS" | awk -F'|' 'NF{print "  - " $1}'
    echo "  - browser (use --browser instead of --bot)"
}

for arg in "$@"; do
    case "$arg" in
        --url=*) URL="${arg#*=}" ;;
        --bot=*) BOT="${arg#*=}" ;;
        --ua=*) CUSTOM_UA="${arg#*=}" ;;
        --expect=*) EXPECT="${arg#*=}" ;;
        --browser) USE_BROWSER=1 ;;
        --list) list_bots; exit 0 ;;
        -v|--verbose) VERBOSE=1 ;;
        -h|--help) print_help; exit 0 ;;
        *)
            echo "Unknown option: $arg" >&2
            print_help
            exit 1
            ;;
    esac
done

if [ -z "$URL" ]; then
    echo "Error: --url is required (or use --list)." >&2
    print_help
    exit 1
fi

run_request() {
    local label="$1" ua="$2" expect="$3"
    local response status headers

    if [ "$VERBOSE" -eq 1 ]; then
        response="$(curl -s -D - -o /tmp/curl_test_body.$$ -A "$ua" "$URL")"
        status="$(echo "$response" | head -n 1 | awk '{print $2}')"
        headers="$response"
    else
        status="$(curl -s -o /dev/null -w '%{http_code}' -A "$ua" "$URL")"
    fi

    local result="PASS"
    local color="\033[0;32m"
    if [ -n "$expect" ] && [ "$status" != "$expect" ]; then
        result="FAIL"
        color="\033[0;31m"
    fi

    printf "%-20s UA: %-70s status: %-5s expect: %-5s ${color}%s\033[0m\n" \
        "$label" "$ua" "$status" "${expect:-any}" "$result"

    if [ "$VERBOSE" -eq 1 ]; then
        echo "--- headers ---"
        echo "$headers"
        echo "---------------"
        rm -f /tmp/curl_test_body.$$
    fi

    [ "$result" = "PASS" ]
}

OVERALL=0

if [ "$USE_BROWSER" -eq 1 ]; then
    exp="${EXPECT:-200}"
    run_request "browser" "$BROWSER_UA" "$exp" || OVERALL=1
elif [ -n "$CUSTOM_UA" ]; then
    exp="${EXPECT:-403}"
    run_request "custom" "$CUSTOM_UA" "$exp" || OVERALL=1
elif [ "$BOT" = "all" ]; then
    exp="${EXPECT:-403}"
    while IFS='|' read -r name ua; do
        [ -z "$name" ] && continue
        run_request "$name" "$ua" "$exp" || OVERALL=1
    done <<< "$(echo "$BOTS" | sed '/^$/d')"
elif [ -n "$BOT" ]; then
    ua="$(lookup_ua "$BOT")"
    if [ -z "$ua" ]; then
        echo "Error: unknown bot '$BOT'. Use --list to see known bots." >&2
        exit 1
    fi
    exp="${EXPECT:-403}"
    run_request "$BOT" "$ua" "$exp" || OVERALL=1
else
    echo "Error: specify --bot=<name>, --bot=all, --ua=\"<string>\", or --browser." >&2
    print_help
    exit 1
fi

exit $OVERALL
